[package]
name = "sample"
version = "0.1.0"
authors = ["hiiragi_ML <shuseiito@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
